/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/matching/rank-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rank Jobs For Profile */
        post: operations["rank_jobs_for_profile_matching_rank_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matching/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Pipeline
         * @description Retrieve candidate jobs, re-rank them, and explain each one.
         *
         *     All three stages of the matching chain: Qdrant retrieval, LLM re-ranking,
         *     then the Match Explanation Agent.
         *
         *     Retrieval itself reads Qdrant rather than SQL, but the session is needed by
         *     the explanation stage, which joins each ranked posting back from SQLite on
         *     `job_id` to recover the skills the Qdrant payload does not carry.
         */
        post: operations["run_pipeline_matching_pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Converse
         * @description Reply to a chat message, possibly editing the profile or starting a run.
         *
         *     Never raises for "the model misbehaved" reasons: the service degrades to a
         *     deterministic reply that still routes a request for matches correctly, so a
         *     missing key or an overloaded model cannot take the chat down.
         */
        post: operations["converse_conversation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Ingestion
         * @description Kick off an ingestion run in the background, returning its id at once.
         */
        post: operations["trigger_ingestion_ingestion_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Current status/counts for a single run (what the dashboard polls).
         */
        get: operations["get_run_ingestion_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description The most recent runs, newest first.
         */
        get: operations["list_runs_ingestion_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Persisted job postings, most recent first, paginated.
         */
        get: operations["list_jobs_ingestion_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Settings
         * @description Create or update a user's notification settings (upsert by user_id).
         */
        post: operations["save_settings_notifications_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/settings/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Read a user's settings. Used by the UI to prefill, and by the
         *     notifications lane to find out where and how to send.
         */
        get: operations["get_settings_notifications_settings__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Cv */
        post: operations["upload_cv_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_cv_upload_post */
        Body_upload_cv_upload_post: {
            /** File */
            file: string;
        };
        /** Contact */
        Contact: {
            /** Email */
            email?: string | null;
            /** Phone Whatsapp */
            phone_whatsapp?: string | null;
        };
        /** ConversationRequest */
        ConversationRequest: {
            /** Message */
            message: string;
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
            /** History */
            history?: components["schemas"]["Turn"][] | null;
        };
        /** ConversationResponse */
        ConversationResponse: {
            /** Intent */
            intent: string;
            /** Reply */
            reply: string;
            /** Updated Profile */
            updated_profile: {
                [key: string]: unknown;
            };
            /** Run Pipeline */
            run_pipeline: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionRunOut */
        IngestionRunOut: {
            /** Id */
            id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Source */
            source: string;
            /** Jobs Fetched */
            jobs_fetched: number;
            /** Jobs Inserted */
            jobs_inserted: number;
            /** Jobs Updated */
            jobs_updated: number;
            /** Jobs Skipped */
            jobs_skipped: number;
            /** Jobs Embedded */
            jobs_embedded: number;
            /** Status */
            status: string;
            /** Error Message */
            error_message: string | null;
        };
        /** JobPosting */
        JobPosting: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Skills */
            skills: string[];
            /** Job Type */
            job_type?: string | null;
            /** Work Mode */
            work_mode?: string | null;
            /** Career Level */
            career_level?: string | null;
            /** Experience Years */
            experience_years?: string | null;
            /** Salary */
            salary?: string | null;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
        };
        /** MatchRequest */
        MatchRequest: {
            profile: components["schemas"]["Profile"];
            /**
             * Top K
             * @default 10
             */
            top_k: number | null;
        };
        /** NotificationSettingsIn */
        NotificationSettingsIn: {
            /**
             * User Id
             * @default default
             */
            user_id: string;
            contact?: components["schemas"]["Contact"] | null;
            /** Notification Channels */
            notification_channels?: string[] | null;
            /** Frequency */
            frequency?: string | null;
            /** Relevance Threshold */
            relevance_threshold?: number | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** NotificationSettingsOut */
        NotificationSettingsOut: {
            /** User Id */
            user_id: string;
            contact: components["schemas"]["Contact"];
            /** Notification Channels */
            notification_channels?: string[];
            /** Frequency */
            frequency?: string | null;
            /** Relevance Threshold */
            relevance_threshold?: number | null;
        };
        /**
         * PipelineRequest
         * @description The UI posts the profile it holds, which is the CV parser's output after
         *     the user has edited it — a free-form dict, not a validated `Profile`. It is
         *     typed loosely on purpose: forcing the UI to satisfy `Profile` (user_id,
         *     experience_years, salary_expectation, ...) would mean inventing values the
         *     parser never produced.
         */
        PipelineRequest: {
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /**
             * Top K
             * @default 10
             */
            top_k: number | null;
        };
        /** PipelineResponse */
        PipelineResponse: {
            /** Ranked */
            ranked: {
                [key: string]: unknown;
            }[];
        };
        /**
         * Profile
         * @description Minimal profile contract consumed by the skill-gap analyzer.
         *
         *     Attributes:
         *         user_id: Identifier of the profile owner.
         *         skills: Raw skill strings as captured from CV/profile intake
         *             (un-normalized; the skill-gap lane normalizes them via
         *             `backend.services.skill_taxonomy`).
         *         target_role: The role the user is targeting (e.g. "Data Analyst").
         *             Matches PRD 7.1 "Capture target roles...".
         *         experience_level: Free-text experience level (e.g. "fresh graduate",
         *             "junior"), matches PRD persona definitions (Section 4).
         */
        Profile: {
            /** User Id */
            user_id: string;
            /** Skills */
            skills?: string[];
            /** Target Role */
            target_role?: string | null;
            /** Experience Level */
            experience_level?: string | null;
        };
        /** RankedJobResponse */
        RankedJobResponse: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location?: string | null;
            /** Work Type */
            work_type?: string | null;
            /** Salary */
            salary?: string | null;
            /** Match Score */
            match_score: number;
            /** Description */
            description?: string | null;
        };
        /** RunIngestionRequest */
        RunIngestionRequest: {
            /** Sources */
            sources?: string[] | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** RunIngestionResponse */
        RunIngestionResponse: {
            /** Run Id */
            run_id: number;
        };
        /** Turn */
        Turn: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /**
         * UploadResponse
         * @description Declared so the generated TypeScript client has a shape to work with.
         *
         *     Without a response_model the OpenAPI schema carries an empty object here,
         *     and `openapi-typescript` produces nothing usable for the one payload the
         *     CV screen is built on.
         *
         *     `profile` stays a loose map on purpose. It is whatever JSON the model
         *     returned, and the parser cannot promise more than that: education and
         *     experience come back as plain strings from some models and as objects from
         *     others. Pinning a stricter shape here would turn a chatty model into a 500
         *     on a request that actually succeeded. The frontend declares its own
         *     tolerant view of this and reads it defensively.
         */
        UploadResponse: {
            /** Message */
            message: string;
            /** Filename */
            filename: string;
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rank_jobs_for_profile_matching_rank_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankedJobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_pipeline_matching_pipeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    converse_conversation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_ingestion_ingestion_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIngestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunIngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_ingestion_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_ingestion_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_ingestion_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPosting"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_settings_notifications_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_notifications_settings__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cv_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_cv_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
