/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/matching/rank-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rank Jobs For Profile */
        post: operations["rank_jobs_for_profile_matching_rank_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matching/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Pipeline
         * @description Retrieve candidate jobs, re-rank them, and explain each one.
         *
         *     All three stages of the matching chain: Qdrant retrieval, LLM re-ranking,
         *     then the Match Explanation Agent.
         *
         *     Retrieval itself reads Qdrant rather than SQL, but the session is needed by
         *     the explanation stage, which joins each ranked posting back from SQLite on
         *     `job_id` to recover the skills the Qdrant payload does not carry.
         */
        post: operations["run_pipeline_matching_pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Converse
         * @description Reply to a chat message, possibly editing the profile or starting a run.
         *
         *     Never raises for "the model misbehaved" reasons: the service degrades to a
         *     deterministic reply that still routes a request for matches correctly, so a
         *     missing key or an overloaded model cannot take the chat down.
         */
        post: operations["converse_conversation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Ingestion
         * @description Kick off an ingestion run in the background, returning its id at once.
         */
        post: operations["trigger_ingestion_ingestion_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Current status/counts for a single run (what the dashboard polls).
         */
        get: operations["get_run_ingestion_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description The most recent runs, newest first.
         */
        get: operations["list_runs_ingestion_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pool Stats
         * @description Aggregate view of the job pool, for the landing page's live snapshot.
         *
         *     `top_tags` are the source's own category tags, counted across postings —
         *     NOT extracted skills. Arbeitnow publishes values like "engineering" and
         *     "marketing", which describe a whole job family rather than a competency,
         *     so anything rendering this must label it as a category. Calling them
         *     skills would overstate what the number means.
         *
         *     Counting happens in Python rather than SQL because `skills` is a
         *     JSON-encoded string in SQLite (see `db_models.JobPostingORM`), so there is
         *     no array to GROUP BY. At a few hundred postings this is not worth a schema
         *     change; if the pool reaches five figures, normalise the tags into their own
         *     table rather than making this query cleverer.
         */
        get: operations["pool_stats_ingestion_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Persisted job postings, most recent first, paginated.
         */
        get: operations["list_jobs_ingestion_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Settings
         * @description Create or update a user's notification settings (upsert by user_id).
         */
        post: operations["save_settings_notifications_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/settings/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Read a user's settings. Used by the UI to prefill, and by the
         *     notifications lane to find out where and how to send.
         */
        get: operations["get_settings_notifications_settings__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/settings/{user_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Profile Snapshot
         * @description Store the matching inputs the scheduled digest will score against.
         *
         *     Called by the frontend once a CV has been parsed. Without it the digest can
         *     only run for a user who happens to have a browser tab open, which is the
         *     opposite of what an unprompted daily notification is for.
         *
         *     404 means no settings row exists yet — save contact details first. The
         *     profile is stored *on* the settings row rather than in its own table
         *     because it is the same single-user demo key, and a second table would need
         *     the same migration when auth lands.
         */
        put: operations["save_profile_snapshot_notifications_settings__user_id__profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preview/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Digest
         * @description Exactly what the next digest would contain — without sending anything.
         *
         *     This is what the settings page renders, so the preview and the message are
         *     produced by the same code rather than by two implementations that can
         *     drift.
         */
        get: operations["preview_digest_notifications_preview__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/send-test/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Test Digest
         * @description Send this user's digest right now, bypassing the once-per-day guard.
         *
         *     `force=True` so someone testing their own setup is not told "already sent
         *     today" — which is the single most confusing thing a test button can say.
         */
        post: operations["send_test_digest_notifications_send_test__user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Dispatch
         * @description Run the whole digest on demand — for the demo, and for debugging.
         *
         *     The most dangerous route in this feature: it reaches every user on record.
         *     `require_admin_token` is what stands in front of it, and in any deployment
         *     that can actually send, that means `NOTIFICATIONS_ADMIN_TOKEN` must be set
         *     or this returns 503. See authz.py and docs/notifications.md.
         */
        post: operations["trigger_dispatch_notifications_dispatch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/scheduler": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scheduler Status */
        get: operations["scheduler_status_notifications_scheduler_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Provider Status
         * @description Which channels are actually usable right now.
         *
         *     The first thing to check when a digest does not arrive.
         */
        get: operations["provider_status_notifications_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Logs
         * @description Recent delivery attempts, newest first. Failures included — they are the
         *     ones worth reading.
         */
        get: operations["recent_logs_notifications_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Cv */
        post: operations["upload_cv_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skill-gap/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Analyze the skill gap for a user against a target role.
         *
         *     Request body example:
         *         {
         *           "user_id": "u123",
         *           "target_role": "Data Analyst",
         *           "skills": ["Python", "excel"],
         *           "job_postings_skills": [["Python", "SQL", "Power BI"]]
         *         }
         *
         *     Response example:
         *         {
         *           "user_id": "u123",
         *           "target_role": "Data Analyst",
         *           "required_skills": ["Python", "SQL", "Power BI"],
         *           "held_skills": ["Python", "Excel"],
         *           "matched_skills": ["Python"],
         *           "gaps": [
         *             {
         *               "skill": "SQL",
         *               "category": "language",
         *               "priority": 1,
         *               "reason": "..."
         *             },
         *             {
         *               "skill": "Power BI",
         *               "category": "tool",
         *               "priority": 2,
         *               "reason": "..."
         *             }
         *           ]
         *         }
         *
         *     Error cases:
         *         400 - neither job_postings_skills nor required_skills supplied.
         */
        post: operations["analyze_skill_gap_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-insight/top-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Top Matches Insight
         * @description Receive the shortlist, delegate to the Job Insight Agent service,
         *     and return its result.
         *
         *     Per CONTRIBUTING.md "Code Organization Rules", this handler holds
         *     no business logic of its own: it only translates the request body
         *     into the service's input models (`Profile` / `MatchedJob` - plain
         *     data, no computation) and translates
         *     `job_insight_agent.generate_job_insights`'s return value into the
         *     response body. All annotation logic (Gemini calls, retries,
         *     completeness validation, fallback, summary formatting) lives in
         *     `backend.services.job_insight_agent`.
         *
         *     Request body example:
         *         {
         *           "user_id": "u123",
         *           "target_role": "Backend Developer",
         *           "skills": ["Python", "FastAPI", "Docker"],
         *           "matched_jobs": [
         *             {
         *               "job_id": "job-1", "title": "Backend Developer",
         *               "company": "Acme Corp",
         *               "required_skills": ["Python", "REST APIs", "Docker", "PostgreSQL"],
         *               "match_score": 82,
         *               "matched_skills": ["Python", "Docker"],
         *               "missing_skills": ["REST APIs", "PostgreSQL"]
         *             }
         *           ]
         *         }
         *
         *     Response shape: `jobs` - the original job objects enriched in place
         *     (see `backend.models.job_insight.JobInsight.to_dict`), not a
         *     separate insights array - and `ui_summary` (see
         *     `backend.services.job_insight_agent.build_ui_summary`).
         */
        post: operations["top_matches_insight_job_insight_top_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_cv_upload_post */
        Body_upload_cv_upload_post: {
            /** File */
            file: string;
        };
        /** Contact */
        Contact: {
            /** Email */
            email?: string | null;
            /** Phone Whatsapp */
            phone_whatsapp?: string | null;
        };
        /** ConversationRequest */
        ConversationRequest: {
            /** Message */
            message: string;
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
            /** History */
            history?: components["schemas"]["Turn"][] | null;
        };
        /** ConversationResponse */
        ConversationResponse: {
            /** Intent */
            intent: string;
            /** Reply */
            reply: string;
            /** Updated Profile */
            updated_profile: {
                [key: string]: unknown;
            };
            /** Run Pipeline */
            run_pipeline: boolean;
        };
        /**
         * DeliveryResult
         * @description Outcome of a single send attempt on a single channel.
         */
        DeliveryResult: {
            /** Channel */
            channel: string;
            /** Provider */
            provider: string;
            /** Success */
            success: boolean;
            /** Message Id */
            message_id?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * DispatchSummary
         * @description Result of one full run across all users — what the API and logs report.
         */
        DispatchSummary: {
            /**
             * Run Started At
             * Format: date-time
             */
            run_started_at: string;
            /**
             * Run Finished At
             * Format: date-time
             */
            run_finished_at: string;
            /**
             * Users Considered
             * @default 0
             */
            users_considered: number;
            /**
             * Users Notified
             * @default 0
             */
            users_notified: number;
            /**
             * Users Skipped No Contact
             * @default 0
             */
            users_skipped_no_contact: number;
            /**
             * Users Skipped Already Sent
             * @default 0
             */
            users_skipped_already_sent: number;
            /**
             * Users Skipped No Matches
             * @default 0
             */
            users_skipped_no_matches: number;
            /**
             * Users Skipped No Profile
             * @default 0
             */
            users_skipped_no_profile: number;
            /**
             * Users Skipped No New Matches
             * @default 0
             */
            users_skipped_no_new_matches: number;
            /** Deliveries */
            deliveries?: components["schemas"]["DeliveryResult"][];
            /** Errors */
            errors?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionRunOut */
        IngestionRunOut: {
            /** Id */
            id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Source */
            source: string;
            /** Jobs Fetched */
            jobs_fetched: number;
            /** Jobs Inserted */
            jobs_inserted: number;
            /** Jobs Updated */
            jobs_updated: number;
            /** Jobs Skipped */
            jobs_skipped: number;
            /** Jobs Embedded */
            jobs_embedded: number;
            /** Status */
            status: string;
            /** Error Message */
            error_message: string | null;
        };
        /** JobPosting */
        JobPosting: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Skills */
            skills: string[];
            /** Job Type */
            job_type?: string | null;
            /** Work Mode */
            work_mode?: string | null;
            /** Career Level */
            career_level?: string | null;
            /** Experience Years */
            experience_years?: string | null;
            /** Salary */
            salary?: string | null;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
        };
        /** MatchRequest */
        MatchRequest: {
            profile: components["schemas"]["Profile"];
            /**
             * Top K
             * @default 10
             */
            top_k: number | null;
        };
        /**
         * MatchedJobRequest
         * @description One entry of the Matching Engine's already-computed shortlist.
         *
         *     Mirrors `backend.models.job_insight.MatchedJob` exactly - this
         *     route performs no matching or scoring of its own, it only accepts
         *     what the Matching Engine already produced.
         */
        MatchedJobRequest: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            /** Company */
            company?: string | null;
            /** Required Skills */
            required_skills?: string[];
            /** Match Score */
            match_score: number;
            /** Matched Skills */
            matched_skills?: string[];
            /** Missing Skills */
            missing_skills?: string[];
        };
        /** NotificationLogOut */
        NotificationLogOut: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /** Channel */
            channel: string;
            /** Provider */
            provider?: string | null;
            /** Status */
            status: string;
            /**
             * Job Ids
             * @default []
             */
            job_ids: string[];
            /** Error Message */
            error_message?: string | null;
            /** Sent On Local Date */
            sent_on_local_date: string;
        };
        /** NotificationSettingsIn */
        NotificationSettingsIn: {
            /**
             * User Id
             * @default default
             */
            user_id: string;
            contact?: components["schemas"]["Contact"] | null;
            /** Notification Channels */
            notification_channels?: string[] | null;
            /** Frequency */
            frequency?: string | null;
            /** Relevance Threshold */
            relevance_threshold?: number | null;
            /** Full Name */
            full_name?: string | null;
            /** Send Hour Local */
            send_hour_local?: number | null;
            /** Timezone */
            timezone?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** NotificationSettingsOut */
        NotificationSettingsOut: {
            /** User Id */
            user_id: string;
            contact: components["schemas"]["Contact"];
            /** Notification Channels */
            notification_channels?: string[];
            /** Frequency */
            frequency?: string | null;
            /** Relevance Threshold */
            relevance_threshold?: number | null;
            /** Full Name */
            full_name?: string | null;
            /** Send Hour Local */
            send_hour_local?: number | null;
            /** Timezone */
            timezone?: string | null;
        };
        /**
         * PipelineRequest
         * @description The UI posts the profile it holds, which is the CV parser's output after
         *     the user has edited it — a free-form dict, not a validated `Profile`. It is
         *     typed loosely on purpose: forcing the UI to satisfy `Profile` (user_id,
         *     experience_years, salary_expectation, ...) would mean inventing values the
         *     parser never produced.
         */
        PipelineRequest: {
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
            /**
             * Top K
             * @default 10
             */
            top_k: number | null;
        };
        /** PipelineResponse */
        PipelineResponse: {
            /** Ranked */
            ranked: {
                [key: string]: unknown;
            }[];
        };
        /**
         * PoolStats
         * @description A read-only snapshot of what has actually been ingested.
         *
         *     Every number here is counted from `job_postings` at request time. Nothing
         *     is estimated, cached, or rounded up — the landing page renders this as
         *     evidence that the pipeline is real, so a figure that drifted from the
         *     table would be worse than showing nothing.
         */
        PoolStats: {
            /** Total Postings */
            total_postings: number;
            /** Distinct Tags */
            distinct_tags: number;
            /** Sources */
            sources: components["schemas"]["SourceCount"][];
            /** Top Tags */
            top_tags: components["schemas"]["TagCount"][];
            /** Last Ingested At */
            last_ingested_at: string | null;
        };
        /**
         * Profile
         * @description Minimal profile contract consumed by the skill-gap analyzer.
         *
         *     Attributes:
         *         user_id: Identifier of the profile owner.
         *         skills: Raw skill strings as captured from CV/profile intake
         *             (un-normalized; the skill-gap lane normalizes them via
         *             `backend.services.skill_taxonomy`).
         *         target_role: The role the user is targeting (e.g. "Data Analyst").
         *             Matches PRD 7.1 "Capture target roles...".
         *         experience_level: Free-text experience level (e.g. "fresh graduate",
         *             "junior"), matches PRD persona definitions (Section 4).
         */
        Profile: {
            /** User Id */
            user_id: string;
            /** Skills */
            skills?: string[];
            /** Target Role */
            target_role?: string | null;
            /** Experience Level */
            experience_level?: string | null;
        };
        /**
         * ProfileSnapshotIn
         * @description The profile the digest scores against.
         *
         *     Loosely typed on purpose, exactly as `PipelineRequest` in the matching
         *     routes is: this is the CV parser's output after the user has edited it, and
         *     forcing it through a strict model would mean inventing values the parser
         *     never produced.
         */
        ProfileSnapshotIn: {
            /** Profile */
            profile: {
                [key: string]: unknown;
            };
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Channel */
            channel: string;
            /** Name */
            name: string;
            /** Configured */
            configured: boolean;
            /**
             * Delivers
             * @default true
             */
            delivers: boolean;
            /** Note */
            note?: string | null;
        };
        /** RankedJobResponse */
        RankedJobResponse: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location?: string | null;
            /** Work Type */
            work_type?: string | null;
            /** Salary */
            salary?: string | null;
            /** Match Score */
            match_score: number;
            /** Description */
            description?: string | null;
        };
        /** RunIngestionRequest */
        RunIngestionRequest: {
            /** Sources */
            sources?: string[] | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** RunIngestionResponse */
        RunIngestionResponse: {
            /** Run Id */
            run_id: number;
        };
        /** SendResult */
        SendResult: {
            /** Outcome */
            outcome: string;
            /**
             * Results
             * @default []
             */
            results: {
                [key: string]: unknown;
            }[];
        };
        /** SkillGapItemResponse */
        SkillGapItemResponse: {
            /** Skill */
            skill: string;
            /** Category */
            category: string | null;
            /** Priority */
            priority: number;
            /** Reason */
            reason: string;
        };
        /**
         * SkillGapRequest
         * @description Request body for POST /skill-gap/analyze.
         *
         *     Either `job_postings_skills` or `required_skills` must be provided
         *     (mirrors `analyze_skill_gap`'s two supported modes).
         */
        SkillGapRequest: {
            /** User Id */
            user_id: string;
            /** Target Role */
            target_role?: string | null;
            /** Experience Level */
            experience_level?: string | null;
            /**
             * Skills
             * @description Raw skills held by the user
             */
            skills?: string[];
            /**
             * Job Postings Skills
             * @description Raw skill lists, one per job posting, used as the demand signal.
             */
            job_postings_skills?: string[][] | null;
            /**
             * Required Skills
             * @description Explicit required-skill override, used instead of job postings.
             */
            required_skills?: string[] | null;
            /**
             * Use Semantic Matching
             * @description If true, run an optional Gemini semantic-matching pass on top of the deterministic taxonomy comparison, to catch equivalences the static alias table doesn't know about yet (e.g. 'FastAPI' ~ 'REST API Development'). Defaults to false: the deterministic-only behavior is unchanged unless a caller opts in.
             * @default false
             */
            use_semantic_matching: boolean;
        };
        /** SkillGapResponse */
        SkillGapResponse: {
            /** User Id */
            user_id: string;
            /** Target Role */
            target_role: string;
            /** Required Skills */
            required_skills: string[];
            /** Held Skills */
            held_skills: string[];
            /** Matched Skills */
            matched_skills: string[];
            /** Gaps */
            gaps: components["schemas"]["SkillGapItemResponse"][];
        };
        /** SourceCount */
        SourceCount: {
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /** TagCount */
        TagCount: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /**
         * TopJobMatch
         * @description One ranked job, as delivered to the user.
         */
        TopJobMatch: {
            job: components["schemas"]["JobPosting"];
            /** Match Score */
            match_score: number;
            /**
             * Reason
             * @description Plain-language fit explanation (PRD 7.5). Populated from the Match Explanation Agent's `overall_alignment_summary` when the pipeline produced one; None on the scorer fallback path, which has no explanation to give.
             */
            reason?: string | null;
        };
        /**
         * TopMatchesInsightRequest
         * @description Request body for POST /job-insight/top-matches.
         */
        TopMatchesInsightRequest: {
            /** User Id */
            user_id: string;
            /** Target Role */
            target_role?: string | null;
            /** Experience Level */
            experience_level?: string | null;
            /**
             * Skills
             * @description Raw skills held by the user
             */
            skills?: string[];
            /**
             * Matched Jobs
             * @description The Matching Engine's already-ranked shortlist (today, the Top 3).
             */
            matched_jobs: components["schemas"]["MatchedJobRequest"][];
        };
        /**
         * TopMatchesInsightResponse
         * @description Response body for POST /job-insight/top-matches.
         *
         *     Deliberately untyped-past-the-top-level (`Dict[str, Any]` for each
         *     job / for `ui_summary`) rather than re-declaring
         *     `backend.models.job_insight.JobInsight` and
         *     `job_insight_agent.build_ui_summary`'s shapes as a second set of
         *     Pydantic models here - that would be exactly the kind of duplicated
         *     business-logic-shape this refactor is meant to avoid. The service
         *     layer (`generate_job_insights`) is the single source of truth for
         *     both shapes; this model only documents the two top-level keys.
         *
         *     `jobs` is each ORIGINAL job object, enriched in place - not a
         *     parallel/separate "insights" array. Every existing job field
         *     (job_id, title, company, required_skills, match_score,
         *     matched_skills, missing_skills) is preserved unchanged; only
         *     `strength`, `weakness`, and `recommendation` are appended to it -
         *     see `backend.models.job_insight.JobInsight.to_dict`.
         */
        TopMatchesInsightResponse: {
            /**
             * Jobs
             * @description One entry per shortlisted job - the ORIGINAL job object (job_id, title, company, required_skills, match_score, matched_skills, missing_skills), enriched in place with the appended strength/weakness/recommendation. Not a separate 'insights' array - see backend.models.job_insight.JobInsight.
             */
            jobs: {
                [key: string]: unknown;
            }[];
            /**
             * Ui Summary
             * @description The same jobs, pre-formatted for direct UI rendering - see backend.services.job_insight_agent.build_ui_summary.
             */
            ui_summary: {
                [key: string]: unknown;
            };
        };
        /** Turn */
        Turn: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /**
         * UploadResponse
         * @description Declared so the generated TypeScript client has a shape to work with.
         *
         *     Without a response_model the OpenAPI schema carries an empty object here,
         *     and `openapi-typescript` produces nothing usable for the one payload the
         *     CV screen is built on.
         *
         *     `profile` stays a loose map on purpose. It is whatever JSON the model
         *     returned, and the parser cannot promise more than that: education and
         *     experience come back as plain strings from some models and as objects from
         *     others. Pinning a stricter shape here would turn a chatty model into a 500
         *     on a request that actually succeeded. The frontend declares its own
         *     tolerant view of this and reads it defensively.
         */
        UploadResponse: {
            /** Message */
            message: string;
            /** Filename */
            filename: string;
            /** Profile */
            profile?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rank_jobs_for_profile_matching_rank_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankedJobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_pipeline_matching_pipeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    converse_conversation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_ingestion_ingestion_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIngestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunIngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_ingestion_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_ingestion_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pool_stats_ingestion_stats_get: {
        parameters: {
            query?: {
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_ingestion_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPosting"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_settings_notifications_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_notifications_settings__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_profile_snapshot_notifications_settings__user_id__profile_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileSnapshotIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_digest_notifications_preview__user_id__get: {
        parameters: {
            query?: {
                top_n?: number;
                /** @description Include jobs already sent in the last 7 days. */
                include_recent?: boolean;
            };
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopJobMatch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_test_digest_notifications_send_test__user_id__post: {
        parameters: {
            query?: {
                /** @description Render and pick a channel, but do not transmit. */
                dry_run?: boolean;
            };
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_dispatch_notifications_dispatch_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
                /** @description Ignore the once-per-day guard. */
                force?: boolean;
                /** @description Only send to users whose local send hour is now. The scheduler sets this True; manual runs default False. */
                respect_send_hour?: boolean;
            };
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scheduler_status_notifications_scheduler_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    provider_status_notifications_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"][];
                };
            };
        };
    };
    recent_logs_notifications_logs_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                limit?: number;
            };
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationLogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cv_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_cv_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_skill_gap_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillGapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillGapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    top_matches_insight_job_insight_top_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopMatchesInsightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopMatchesInsightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
