/**
 * Domain types.
 *
 * Anything the backend describes properly is taken from the generated schema
 * rather than retyped, so a backend change becomes a build error here instead
 * of a blank screen at runtime. `schema.d.ts` is generated by `npm run gen:api`
 * from `backend/openapi.json`; do not edit it by hand.
 */
import type { components } from "./schema";

type Schemas = components["schemas"];

export type NotificationSettings = Schemas["NotificationSettingsOut"];
export type Contact = Schemas["Contact"];
export type IngestionRun = Schemas["IngestionRunOut"];
export type RunIngestionResponse = Schemas["RunIngestionResponse"];
export type PipelineResponse = Schemas["PipelineResponse"];
export type ConversationResponse = Schemas["ConversationResponse"];
export type Turn = Schemas["Turn"];
export type JobPosting = Schemas["JobPosting"];
export type UploadResponse = Schemas["UploadResponse"];

/**
 * The parsed CV profile.
 *
 * Everything is optional and several fields are deliberately loose. This is
 * whatever JSON the model returned: `education` and `experience` come back as
 * a plain string from some models and as a list from others, and the backend
 * does not normalise them because rejecting a chatty model would turn a
 * successful parse into a 500. The UI coerces with `asList` / `asText` in
 * `lib/profile.ts` rather than trusting either shape.
 */
export interface Profile {
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  title?: string | null;
  current_title?: string | null;
  skills?: string[] | string | null;
  education?: string[] | string | null;
  experience?: string[] | string | null;
  [key: string]: unknown;
}

/** One job's written explanation, from the Match Explanation Agent. Every list
 *  defaults to empty, so a partially populated response has to render cleanly
 *  rather than showing empty headings. */
export interface MatchExplanation {
  overall_alignment_summary?: string | null;
  strengths?: string[] | null;
  gaps_or_missing_requirements?: string[] | null;
  recommendations?: string[] | null;
  next_steps?: string[] | null;
}

/** One ranked match, flattened for display. Mirrors the shape
 *  `streamlit_app/pipeline_stub.py` produces from the pipeline's `ranked`. */
export interface MatchResult {
  job_id?: string;
  job_title: string;
  company: string;
  location?: string | null;
  description?: string | null;
  required_skills?: string[] | null;
  url?: string | null;
  fit_score?: number | null;
  match_score?: number | null;
  date_posted?: string | null;
  explanation?: MatchExplanation | null;
}

/** One entry in the Trigger Now digest. */
export interface Recommendation {
  job_title: string;
  company: string;
  url: string | null;
}

/** A visible chat turn. */
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}
